### ISSUE TITLE
I have no rights for even a pull-request... wanted to submit a short readme.md

### ISSUE THREAD

**Issue by gernotstarke** [perstarke-webdev/oneflow-jekyll-theme#31]

**Comment by Per-Starke** [comment]
Invited you with write-access.

Thanks!

Maybe you can also add the link to the first short example-site I've created, about my BA. I'll create second short example site for the Homepage Canvas. 

[https://oneflow-jekyll-theme-example-one.github.io/](https://oneflow-jekyll-theme-example-one.github.io/)

**Comment by Per-Starke** [comment]
Would you suggest putting the full documentation (to be created) as the readme here, or just leave it with a short readme and put the full docu on my website?

**Comment by gernotstarke** [comment]
please add the link to your newly created site yourself :-)
(you mean to the canvas site, don't you?)

**Comment by gernotstarke** [comment]
push worked

**Comment by gernotstarke** [comment]
> please add the link to your newly created site yourself :-) (you mean to the canvas site, don't you?)



> Would you suggest putting the full documentation (to be created) as the readme here, or just leave it with a short readme and put the full docu on my website?

**not thought it through, therefore I keep my mouth shut**

**Comment by Per-Starke** [comment]
Thanks!
