### ISSUE TITLE
make startup easier by providing .zip download of required files

### ISSUE THREAD

**Issue by gernotstarke** [perstarke-webdev/oneflow-jekyll-theme#34]
People who want to use this theme should NOT be forced to fork & clone the repo first, as a simple download
of the required files is sufficient.

Therefore, provide a .zip download, please...

**Comment by gernotstarke** [comment]
yes, I know that people can download the whole repo from the github page... but I meant a download button on your https://oneflow-jekyll-theme.github.io/ site

**Comment by Per-Starke** [comment]
Great input, thanks!
